#' Transboundary movements network
#'
#' This function analyzes the dataset generated by the impcheckdata function and
#' produces an international mobility network with respect to a given country.
#' This network contains movements between the reference country and other countries.
#'
#' Cette fonction analyse le jeu de données généré par la fonction impcheckdata
#' et produit un réseau de mobilité internationale par rapport à un pays donné.
#' Ce réseau contient les mouvements entre le pays de référence et d'autres pays.
#'
#'
#' @import igraph
#' @importFrom graphics plot
#' @export mobinternat
#' @param x the data.frame containing the rawdata and generated by the impcheckdata function. \cr
#' Required columns: "ORIGIN_NAME", "ORIGIN_COUNTRY", "ORIGIN_LONGITUDE_X", "ORIGIN_LATITUDE_Y",
#' "DESTINATION_NAME", "DESTINATION_COUNTRY", "DESTINATION_LONGITUDE_X", "DESTINATION_LATITUDE_Y" and "HEADCOUNT"
#' 
#' @param my_country the reference country between quotation marks, with the same writting than in x.
#' @keywords international movements network
#' 
#' @examples
#' mobinternat(rawdata, "TUNISIA")
#'
mobinternat <- function(x, my_country){
  Origins <- x[,c("ORIGIN_NAME", "ORIGIN_COUNTRY", "ORIGIN_LONGITUDE_X", "ORIGIN_LATITUDE_Y")]
  Destinations <- x[,c("DESTINATION_NAME", "DESTINATION_COUNTRY", "DESTINATION_LONGITUDE_X", "DESTINATION_LATITUDE_Y")]
  names(Origins) <- names(Destinations) <- c("NAME","COUNTRY","LONGITUDE_X", "LATITUDE_Y")
  Origins$NAME <- as.character(Origins$NAME)
  Origins$COUNTRY <- as.character(Origins$COUNTRY)
  Destinations$NAME <- as.character(Destinations$NAME)
  Destinations$COUNTRY <- as.character(Destinations$COUNTRY)
  Places <- unique(rbind(Origins, Destinations))
  Name_Places <- unique(Places$NAME)
  x_tmp <- x[x$DESTINATION_COUNTRY == my_country & x$ORIGIN_COUNTRY != my_country,]
  Internatl_net <- graph_from_data_frame(x_tmp[,c("ORIGIN_NAME","DESTINATION_NAME")],
                                              vertices=Name_Places, directed=TRUE)
  E(Internatl_net)$weight <- x_tmp[,c("HEADCOUNT")]
  plot(Internatl_net)
  Internatl_net
}
