#' National movements network
#'
#' Function to analyze the dataset generated by the impcheckdata function and
#' produces a national mobility network with respect to a given country.
#' This network contains movements inside a given country.
#'
#' Cette fonction analyse le jeu de données généré par la fonction impcheckdata
#' et produit un réseau de mobilité nationale par rapport à un pays donné.
#' Ce réseau contient les mouvements ayant lieu à l'intérieur du pays de référence.
#'
#' @import igraph
#' @importFrom graphics plot
#' @export mobnation
#' @param x the data.frame containing the rawdata and generated by the impcheckdata function. \cr
#' Required columns: "ORIGINE_NOM", "ORIGINE_PAYS", "ORIGINE_LONGITUDE_X", "ORIGINE_LATITUDE_Y",
#' "DESTINATION_NOM", "DESTINATION_PAYS", "DESTINATION_LONGITUDE_X", "DESTINATION_LATITUDE_Y" and "EFFFECTIF"
#'
#' @param mon_pays the reference country between quotation marks, with the same writting than in x.
#' @keywords national movements network
#'
#' @examples
#' mobnation(rawdata, "TUNISIE")
#'
mobnation <- function(x, mon_pays){
  Origins <- x[,c("ORIGIN_NAME", "ORIGIN_COUNTRY", "ORIGIN_LONGITUDE_X", "ORIGIN_LATITUDE_Y")]
  Destinations <- x[,c("DESTINATION_NAME", "DESTINATION_COUNTRY", "DESTINATION_LONGITUDE_X", "DESTINATION_LATITUDE_Y")]
  names(Origins) <- names(Destinations) <- c("NAME","COUNTRY","LONGITUDE_X", "LATITUDE_Y")
  Origins$NAME <- as.character(Origins$NAME)
  Origins$COUNTRY <- as.character(Origins$COUNTRY)
  Destinations$NAME <- as.character(Destinations$NAME)
  Destinations$COUNTRY <- as.character(Destinations$COUNTRY)
  Places <- unique(rbind(Origins, Destinations))
  Name_Places <- unique(Places$NAME)
  x_tmp <- x[x$DESTINATION_COUNTRY == my_country & x$ORIGIN_COUNTRY == my_country,]
  Natl_net <- graph_from_data_frame(x_tmp[,c("ORIGIN_NAME","DESTINATION_NAME")],
                                         vertices=Name_Places, directed=TRUE)
  E(Natl_net)$weight <- x_tmp[,c("HEADCOUNT")]
  Natl_net
}
