#' SNA parameters
#'
#' This function returns a data.frame with four mobility parameters computed for each locality:
#' the degree centralities (degree, in-degree, and out-degree) and the betweenness centralities.
#'
#' Cette fonction 4 paramètres de mobilité pour chaque localité :
#' le degré, le degré entrant et le degré sortant et la centralité d'intermédiarité.
#'
#'
#' @import igraph
#' @export paramSNA
#' @param x the network generated by one of the mobinternat and mobnation functions.
#' @param y the data.frame containing the rawdata and generated by the impcheckdata function. \cr
#' Required columns: "ORIGIN_NAME", "ORIGIN_COUNTRY", "ORIGIN_LONGITUDE_X", "ORIGIN_LATITUDE_Y",
#' "DESTINATION_NAME", "DESTINATION_COUNTRY", "DESTINATION_LONGITUDE_X", "DESTINATION_LATITUDE_Y" and "HEADCOUNT"
#'
#' @param my_country the reference country between quotation marks, with the same writting than in y.
#' @keywords parameters sna network
#'
paramSNA <- function(x, y, my_country){
  ORIGINs <- y[,c("ORIGIN_NAME", "ORIGIN_COUNTRY", "ORIGIN_LONGITUDE_X", "ORIGIN_LATITUDE_Y")]
  Destinations <- y[,c("DESTINATION_NAME", "DESTINATION_COUNTRY", "DESTINATION_LONGITUDE_X", "DESTINATION_LATITUDE_Y")]
  names(ORIGINs) <- names(Destinations) <- c("NAME","COUNTRY","LONGITUDE_X", "LATITUDE_Y")
  ORIGINs$NAME <- as.character(ORIGINs$NAME)
  ORIGINs$COUNTRY <- as.character(ORIGINs$COUNTRY)
  Destinations$NAME <- as.character(Destinations$NAME)
  Destinations$COUNTRY <- as.character(Destinations$COUNTRY)
  Places <- unique(rbind(ORIGINs, Destinations))
  deg     <- strength(x, mode="all")
  indeg   <- strength(x, mode="in")
  outdeg  <- strength(x, mode="out")
  betw    <- betweenness(x, directed=T, weights=E(x)$weight)
  betw2   <- edge_betweenness(x, directed=T, weights=E(x)$weight)
  sna     <- Reduce(MyMerge, list(deg, indeg, outdeg, betw))
  names(sna) <- as.factor(c("degree", "indegree", "outdegree", "betweeness"))
  sna     <- data.frame(sna)
  sna$NAME <- row.names(sna)
  sna     <- merge(sna, Places, by='NAME')
  sna[sna$COUNTRY == my_country,]
}
